backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: static/assets
public_folder: /assets

collections:
  - name: "parallax"
    identifier_field: templateKey
    label: "Parallax Section"
    folder: "src/sections/parallax"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "parallax-section"}
      - {label: "Backgraund Image", name: "backgraundImg", widget: "image"}

  - name: "home"
    identifier_field: templateKey
    label: "Home Section"
    folder: "src/sections/home"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-section"}
      - {label: "Author Name", name: "authorName", widget: "string"}
      - {label: "Media Video BGR", name: "video-bgr", widget: "file"}

  - name: "about"
    identifier_field: templateKey
    label: "About Section"
    folder: "src/sections/about"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-section"}
      - {label: "Author Name", name: "authorName", widget: "string"}
      - {label: "Author Pick", name: "authorPick", widget: "image"}
      - {label: "About Description", name: "description", widget: "markdown"}