backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "home"
    label: "Home Section"
    folder: "src/sections/home"
    create: true
    #slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-section"}
      - {label: "Author Name", name: "authorName", widget: "string"}
      - {label: "About Description", name: "description", widget: "markdown"}