backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img


collections:
  - name: "About"
    label: "About info"
    description: "About information"
    folder: "src/cms"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
